### ISSUE TITLE
Can we please have 1.12 support too?

### ISSUE THREAD

**Issue by RealmportalMC** [SugarCaney/CrystalQuest#3]
I see the issue was closed, but my MG server is stuck on 1.12.2 and ive been hoping this would be updated for the longest time,

I understand its more work, but it would allow more people to use it. LOTS of my servers minigame plugins break on 1.13.x :/

**Comment by SugarCaney** [comment]
I could take a look at it. It's just a hassle because I have to change up my development setup once again. I'll let you know when I find something. Note that if a 1.12 version comes out, I won't be supporting it. All bug fixes and enhancements will be applied to the 1.13 fork. It will basically be a clone of the 1.11 with resolved 1.12 compatibility fixes.

In the end, I just have to move forward. I know that the leap to 1.13 is annoying, because the whole material API changed. I hope many plugins will port over nicely kind of soon-ish. You can always use BungeeCord to hop between different server versions.

EDIT: I will be supporting 1.14. That would hopefully not be too much work.

**Comment by SugarCaney** [comment]
[I made the 1.12.2 port, let me know if you have issues](https://github.com/SugarCaney/CrystalQuest-1.12.2/releases/tag/v1.3.1)

**Comment by RealmportalMC** [comment]
> 
> 
> [I made the 1.12.2 port, let me know if you have issues](https://github.com/SugarCaney/CrystalQuest-1.12.2/releases/tag/v1.3.1)

Thank you very much. im not concerned about new features and such. simply a version which is compatible.  im in a situation where i cant have too many backend servers, i already have 3 and a bungeecord Not to mention all of my maps are 1.12 updated
